# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

project:
  name: batch-protein-folding
  package_lambda: false
  s3_bucket: aws-batch-architecture-for-alphafold-public-artifacts
  regions:
    - us-east-1
    - us-east-2
    - us-west-2
  parameters:
    Environment: dev
tests:
  default:
    template: infrastructure/cloudformation/batch-protein-folding-cfn-packaged.yaml
