# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  batch-protein-folding-cfn-root.yaml: Root stack for running protein folding on AWS Batch

Parameters:
  ApplicationName:
    Type: String
    Default: BatchProteinFolding
  LaunchSageMakerNotebook:
    Type: String
    Default: Y
    Description: Create a SageMaker Notebook Instance.
    AllowedValues: [Y, N]       
  StackAvailabilityZone:
    Type: String
    AllowedValues: [a, b, c]
    Default: a     
  VPC:
    Description: (Optional) ID of VPC to use. If left empty, a new VPC will be created.
    Type: String
    Default: ""     
  Subnet:
    Description: (Optional) ID of private subnet to use. If left empty, a new VPC will be created.
    Type: String
    Default: ""     
  DefaultSecurityGroup:
    Description: (Optional) ID of security group to use. If left empty, a new VPC will be created.
    Type: String
    Default: ""
  FileSystemId:
    Description: (Optional) ID of FSX for Lustre  to use. If left empty, a new FSx for Lustre instance will be created.
    Type: String
    Default: ""
  FileSystemMountName:
    Description: (Optional) Mount name of FSX for Lustre to use. If left empty, a new FSx for Lustre instance will be created.
    Type: String
    Default: ""    
  DownloadFsxData:
    Description: Automatically populate FSx for Lustre file system with model parameters and sequence databases?
    Type: String
    Default: "Y"
    AllowedValues: [Y, N]
  CreateG5ComputeEnvironment:
    Description: Create a compute environment for G5 instance types? Note that availabilty is region-specific
    Type: String
    Default: "N"
    AllowedValues: [Y, N]    


Conditions:
  CreateFileSystem:
    "Fn::Or":
      [
        "Fn::Equals": [Ref: FileSystemId, ""],
        "Fn::Equals": [Ref: FileSystemMountName, ""],
        "Fn::Equals": [Ref: VPC, ""],
        "Fn::Equals": [Ref: DefaultSecurityGroup, ""],
        "Fn::Equals": [Ref: Subnet, ""],
      ]
  CreateNetwork:
    "Fn::Or":
      [
        "Fn::Equals": [Ref: VPC, ""],
        "Fn::Equals": [Ref: DefaultSecurityGroup, ""],
        "Fn::Equals": [Ref: Subnet, ""],
      ]
  CreateSageMakerNotebook:
    "Fn::Equals": [Ref: "LaunchSageMakerNotebook", "Y"]
  DownloadFsxDataCondition:
    "Fn::Equals": [Ref: "DownloadFsxData", "Y"] 
   

Resources:
  Network:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateNetwork
    Properties:
      TemplateURL: batch-protein-folding-cfn-network.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        StackAvailabilityZone:
          "Fn::Sub": ${AWS::Region}${StackAvailabilityZone}

  FileSystem:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateFileSystem
    Properties:
      TemplateURL: batch-protein-folding-cfn-fsx-lustre.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        DefaultSecurityGroup:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.DefaultSecurityGroup
            - Ref: DefaultSecurityGroup
        FSXForLustreStorageCapacity: 2400
        FSxForLustreThroughput: 500
        Subnet:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.PrivateSubnet
            - Ref: Subnet

  Container:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: batch-protein-folding-cfn-container.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        LambdaSubnet:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.PrivateSubnet
            - Ref: Subnet
        LambdaSecurityGroupId:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.DefaultSecurityGroup
            - Ref: DefaultSecurityGroup        
        DownloadFsxData:
          Ref: DownloadFsxData

  BatchEnvironment:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: batch-protein-folding-cfn-batch.yaml
      Parameters:
        CreateG5ComputeEnvironment:
          Ref: CreateG5ComputeEnvironment
        ApplicationName:
          Ref: ApplicationName
        Subnet:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.PrivateSubnet
            - Ref: Subnet
        DefaultSecurityGroupID:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.DefaultSecurityGroup
            - Ref: DefaultSecurityGroup
        FileSystemId:
          "Fn::If":
            - CreateFileSystem
            - "Fn::GetAtt": FileSystem.Outputs.FileSystemId
            - Ref: FileSystemId
        FileSystemMountName:
          "Fn::If":
            - CreateFileSystem
            - "Fn::GetAtt": FileSystem.Outputs.FileSystemMountName
            - Ref: FileSystemMountName
        DownloadContainerRegistryURI:
          "Fn::GetAtt": Container.Outputs.DownloadContainerRegistryURI
        S3BucketName:
          "Fn::GetAtt": Container.Outputs.s3Bucket

  Notebook:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateSageMakerNotebook
    Properties:
      TemplateURL: batch-protein-folding-cfn-notebook.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        Subnet:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.PrivateSubnet
            - Ref: Subnet
        DefaultSecurityGroupID:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.DefaultSecurityGroup
            - Ref: DefaultSecurityGroup
        CodeRepositoryURI:
          "Fn::GetAtt": Container.Outputs.CodeRepositoryURI    
        S3BucketName:
          "Fn::GetAtt": Container.Outputs.s3Bucket     

  DownloadData:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - BatchEnvironment
    Condition: DownloadFsxDataCondition
    Properties:
      TemplateURL: batch-protein-folding-cfn-download.yaml
      Parameters:
        DownloadJobQueue:
          "Fn::GetAtt": BatchEnvironment.Outputs.GravitonOnDemandJobQueue
        JobDefinition:
          "Fn::GetAtt": BatchEnvironment.Outputs.DownloadJobDefinition
        LambdaSubnet:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.PrivateSubnet
            - Ref: Subnet
        LambdaSecurityGroupId:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.DefaultSecurityGroup
            - Ref: DefaultSecurityGroup             

#################################################################################
# Modules
#################################################################################

  ModuleAlphaFold2:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: batch-protein-folding-cfn-module-alphafold2.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        CodeRepositoryUrl:
            "Fn::GetAtt": Container.Outputs.CodeRepositoryURI
        CodeBuildEncryptionKey:
            "Fn::GetAtt": Container.Outputs.CodeBuildEncryptionKey      
        CodeBuildRoleArn:
            "Fn::GetAtt": Container.Outputs.CodeBuildRoleArn
        StartCodeBuildLambdaArn:
            "Fn::GetAtt": Container.Outputs.StartCodeBuildLambdaArn
        DeleteContainerRepoLambdaArn:
            "Fn::GetAtt": Container.Outputs.DeleteContainerRepoLambdaArn

  ModuleOpenFold:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: batch-protein-folding-cfn-module-openfold.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        CodeRepositoryUrl:
            "Fn::GetAtt": Container.Outputs.CodeRepositoryURI          
        CodeBuildEncryptionKey:
            "Fn::GetAtt": Container.Outputs.CodeBuildEncryptionKey      
        CodeBuildRoleArn:
            "Fn::GetAtt": Container.Outputs.CodeBuildRoleArn
        StartCodeBuildLambdaArn:
            "Fn::GetAtt": Container.Outputs.StartCodeBuildLambdaArn            
        DeleteContainerRepoLambdaArn:
            "Fn::GetAtt": Container.Outputs.DeleteContainerRepoLambdaArn          

  ModuleJackhmmer:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: batch-protein-folding-cfn-module-jackhmmer.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        CodeRepositoryUrl:
            "Fn::GetAtt": Container.Outputs.CodeRepositoryURI          
        CodeBuildEncryptionKey:
            "Fn::GetAtt": Container.Outputs.CodeBuildEncryptionKey      
        CodeBuildRoleArn:
            "Fn::GetAtt": Container.Outputs.CodeBuildRoleArn
        StartCodeBuildLambdaArn:
            "Fn::GetAtt": Container.Outputs.StartCodeBuildLambdaArn            
        DeleteContainerRepoLambdaArn:
            "Fn::GetAtt": Container.Outputs.DeleteContainerRepoLambdaArn      

  ModuleOmegaFold:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: batch-protein-folding-cfn-module-omegafold.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        CodeRepositoryUrl:
            "Fn::GetAtt": Container.Outputs.CodeRepositoryURI          
        CodeBuildEncryptionKey:
            "Fn::GetAtt": Container.Outputs.CodeBuildEncryptionKey      
        CodeBuildRoleArn:
            "Fn::GetAtt": Container.Outputs.CodeBuildRoleArn
        StartCodeBuildLambdaArn:
            "Fn::GetAtt": Container.Outputs.StartCodeBuildLambdaArn            
        DeleteContainerRepoLambdaArn:
            "Fn::GetAtt": Container.Outputs.DeleteContainerRepoLambdaArn   

Outputs:
  ApplicationName:
    Description: Name of the application
    Value:
      Ref: ApplicationName
